name: Tests

on:
    push:
    pull_request:

jobs:
    tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [7.4, 8.0]
                os: [ubuntu-latest]

        name: P${{ matrix.php }} - ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, mbstring, zip, intl, json
                  coverage: none
                  tools: composer:v2

            - name: Install PHP:7.4 dependencies
              run: composer install --no-interaction --no-progress
              if: "matrix.php < 8"

            - name: Install PHP:8 dependencies
              run: composer install --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress
              if: "matrix.php >= 8"

            - name: Execute Tests
              run: composer test
